version: '1'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=auth_score      
    ports:
      - "5432:5432"
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/postgresql/data